---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beszel
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beszel
  template:
    metadata:
      labels:
        app: beszel
    spec:
      containers:
        - name: beszel
          image: henrygd/beszel:latest
          ports:
            - containerPort: 8090
          volumeMounts:
            - name: beszel-data
              mountPath: /beszel_data
      volumes:
        - name: beszel-data
          persistentVolumeClaim:
            claimName: beszel-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beszel-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: beszel-service
  namespace: monitoring
spec:
  selector:
    app: beszel
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beszel-ingress
  namespace: monitoring
spec:
  rules:
    - host: beszel.maybeit.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: beszel-service
                port:
                  number: 8090
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beszel-agent
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: beszel-agent
  template:
    metadata:
      labels:
        app: beszel-agent
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: beszel-agent
          image: henrygd/beszel-agent:latest
          env:
            - name: LISTEN
              value: "45876"
            - name: KEY
              valueFrom:
                secretKeyRef:
                  name: beszel-token
                  key: KEY
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: beszel-token
                  key: TOKEN
            - name: HUB_URL
              value: "http://beszel-service:8090"
