---
name: CI Pipeline

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run ShellCheck and Yamllint
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck yamllint
          shellcheck bootstrap/*.sh
          yamllint .
